name: hakim_app
description: "تطبيق إدارة محل صيانة الهواتف - الأرباح والديون والطلبات"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # إدارة الحالة
  provider: ^6.1.2

  # قاعدة بيانات محلية
  sqflite: ^2.3.3+1
  path: ^1.9.0
  path_provider: ^2.1.3

  # حفظ إعدادات بسيطة (رابط جوجل شيت + PIN)
  shared_preferences: ^2.2.3

  # الاتصال بالإنترنت (لإرسال البيانات لجوجل شيت)
  http: ^1.2.1

  # تنسيق التواريخ والأرقام (بالعربية)
  intl: ^0.19.0

  # تشفير الـ PIN
  crypto: ^3.0.3

  # خط عربي أنيق (Cairo)
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
